name: Build and Deploy via SSH

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔨 Build project
        run: npm run build

      - name: 🚀 Deploy via SSH
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.SSH_HOST }}
          remote-user: ${{ secrets.SSH_USER }}
          private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-port: ${{ secrets.SSH_PORT }}
          destination-path: ${{ secrets.DESTINATION }}
          source-path: out/
          rsync-options: --archive --verbose --compress --human-readable --progress --delete-after --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore --exclude=2048/ --exclude=projects/
